site_name: Tutorial de TwinCAT 3
site_url: https://famoreno.github.io/tc3_tutorial/

theme:
  name: material
  language: es
  custom_dir: docs/overrides
  logo: images/_resource/logo_auto_isa_team.png
  favicon: images/_resource/logo_auto_isa_team.png

  palette:
    - scheme: default
      primary: custom #002e5d #blue grey
      # accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: custom #002e5d  #blue grey
      # accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

  font:
    text: IBM Plex Sans # Roboto
    code: IBM Plex Mono # Roboto Mono

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - 🏠 Inicio: index.md
  - Contenidos generales:
    - ⚙️ Beckhoff y TwinCAT 3: contenidos/00_presentacion.md
    - ✔ Conceptos Generales: contenidos/01_conceptos.md
    - ⚡ Ejecución de Programas: contenidos/01b_ejecucion.md
    - 🅰️ Lenguajes de Implementación: contenidos/01c_lenguajes.md
  - Ejemplos:
    # - ✏️ Descripción general: contenidos/01d_ejemplos.md 
    - 👋 Ej. - Demo: contenidos/02_tc3_demo.md
    - 👋 Ej. - Hola Mundo: contenidos/02_tc3_hola_mundo.md
    - 🛒 Ej. - Carro Básico: contenidos/03_tc3_carro_basico.md
    - 🚟 Ej. - Carro Extendido: 
      - ✏️ Descripción: contenidos/04_tc3_carro_extendido.md
      - 🧱 Monolítico: contenidos/04_tc3_carro_extendido/04_tc3_carro_extendido_mono.md
      - 🗂️ Estructurado: contenidos/04_tc3_carro_extendido/04_tc3_carro_extendido_estructurado.md
      - ⚙️ Jerárquico: contenidos/04_tc3_carro_extendido/04_tc3_carro_extendido_jerarquico.md
      # - 🧩 Impl. Funcional: contenidos/04_tc3_carro_extendido/04_tc3_carro_extendido_funcional.md
  - Prácticas:
    - ℹ️ Información: contenidos/01e_practicas.md 
    - 👋 Demo: contenidos/05_tc3_practicas/05_tc3_demo.md
    - 👋 Hola Mundo: contenidos/05_tc3_practicas/05_tc3_hola_mundo.md
    - 🚦 Semáforo (ArduTC): contenidos/05_tc3_practicas/05_tc3_semaforo.md
    # - 🛒 Carro básico: contenidos/05_tc3_practicas/05_tc3_carro_basico.md
    - 🧩 Proyectos:
      - 🧱 Monolítico: contenidos/05_tc3_practicas/05_tc3_proyecto_mono.md
      - 🗂️ Estructurado: contenidos/05_tc3_practicas/05_tc3_proyecto_estructurado.md
      - ⚙️ Jerárquico: contenidos/05_tc3_practicas/05_tc3_proyecto_jerarquico.md
      # - 🧩 Funcional: contenidos/05_tc3_practicas/05_tc3_proyecto_funcional.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
      base_path: !relative $docs_dir
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      # custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      

plugins:
  - search
  - include-markdown
  - macros:
      include_dir: docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/famoreno/tc3_tutorial

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/ui-course.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js