site_name: Tutorial de TwinCAT 3
site_url: https://famoreno.github.io/tc3_tutorial/

theme:
  name: material
  language: es
  custom_dir: overrides
  logo: assets/img/logo-auto-isa-team.png
  favicon: assets/img/logo-auto-isa-team.png

  palette:
    - scheme: default
      primary: custom #002e5d #blue grey
      # accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: custom #002e5d  #blue grey
      # accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

  font:
    text: IBM Plex Sans # Roboto
    code: IBM Plex Mono # Roboto Mono

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - 🏠 Inicio: index.md

  - 🏛️ Fundamentos:
      - ⚙️ TwinCAT: contenidos/fundamentos/twincat/index.md
      - 🅰️ Lenguajes: contenidos/fundamentos/lenguajes/index.md
      - ✏️ GRAFCET: contenidos/fundamentos/grafcet/index.md
      - 🏗️ Arquitecturas: contenidos/fundamentos/arquitecturas/index.md
      - ArduTC: contenidos/fundamentos/ardutc/index.md

  - 🛠️ Procedimientos:
      - 1️⃣ TwinCAT 3 - Workflow: contenidos/procedimientos/workflow/index.md
      - 🔤 Lenguaje LD: contenidos/procedimientos/ladder/index.md
      - 🔤 Lenguaje SFC: contenidos/procedimientos/sfc/index.md
      - 🖥️ Visualizaciones: contenidos/procedimientos/visu/index.md
  
  - 🔬 Ejemplos:
      - 👋 Hola Mundo: 
          - 📝 Descripción: contenidos/ejemplos/hola-mundo/index.md
          - 🛠️ Guía de Implementación: contenidos/ejemplos/hola-mundo/step-by-step.md
      - 🛒 Carro Básico:
          - 📝 Descripción: contenidos/ejemplos/carro-basico/index.md
          - 🛠️ Guía de Implementación: contenidos/ejemplos/carro-basico/step-by-step.md
      - 🚟 Carro Extendido: 
          - 📝 Descripción: contenidos/ejemplos/carro-extendido/index.md
          - 🛠️ Guía: contenidos/ejemplos/carro-extendido/step-by-step.md
  
  - 📋 Prácticas:
      - 🚦 Semáforo: contenidos/practicas/semaforo/index.md
      - 🔲 Proyecto Monolítico: contenidos/practicas/proyectos/proyecto-monolitico.md
      - 🗄️ Proyecto Estructurado: contenidos/practicas/proyectos/proyecto-estructurado.md
      - 📐 Proyecto Jerárquico: contenidos/practicas/proyectos/proyecto-jerarquico.md
      - 🧩 Proyecto Funcional: contenidos/practicas/proyectos/proyecto-funcional.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
      # base_path: !relative $docs_dir
      base_path: ["docs"]
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      # custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - include-markdown
  - macros:
      include_dir: docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/famoreno/tc3_tutorial

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/ui-course.js
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  