site_name: Tutorial de TwinCAT 3
site_url: https://famoreno.github.io/tc3_tutorial/

exclude_docs: |
  contenidos/ejemplos/carro-basico/includes/**

theme:
  name: material
  language: es
  custom_dir: overrides
  logo: assets/img/logo-auto-isa-team.png
  favicon: assets/img/logo-auto-isa-team.png

  palette:
    - scheme: default
      primary: custom #002e5d #blue grey
      # accent: indigo
      toggle:
        icon: fontawesome/solid/moon
        name: Modo oscuro
    - scheme: slate
      primary: custom #002e5d  #blue grey
      # accent: indigo
      toggle:
        icon: fontawesome/solid/sun
        name: Modo claro

  font:
    text: IBM Plex Sans # Roboto
    code: IBM Plex Mono # Roboto Mono

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
    - ":fontawesome-solid-house: Inicio": index.md

    - ":fontawesome-solid-landmark: Fundamentos":
      - ":fontawesome-solid-gears: TwinCAT": contenidos/fundamentos/twincat/index.md
      - ":fontawesome-solid-language: Lenguajes": contenidos/fundamentos/lenguajes/index.md
      - ":fontawesome-solid-diagram-project: GRAFCET": contenidos/fundamentos/grafcet/index.md
      - ":fontawesome-solid-bolt: DRC": contenidos/fundamentos/reles-contactos/index.md
      - ":fontawesome-solid-sitemap: Arquitecturas": contenidos/fundamentos/arquitecturas/index.md
      - ArduTC: contenidos/fundamentos/ardutc/index.md

    - ":fontawesome-solid-screwdriver-wrench: Procedimientos":
      - ":fontawesome-solid-folder-plus: Crear un Proyecto": contenidos/procedimientos/workflow/index.md
      - ":fontawesome-solid-network-wired: Editar un Ladder": contenidos/procedimientos/ladder/index.md
      - ":fontawesome-solid-diagram-project: Editar un SFC": contenidos/procedimientos/sfc/index.md
      - ":fontawesome-solid-display: Crear una Visualización":
        - ":fontawesome-solid-circle-info: Intoducción": contenidos/procedimientos/hmi/index.md
        - ":fontawesome-solid-bolt: TwinCAT 3 PLC-HMI": contenidos/procedimientos/hmi/tc3-plc-hmi.md
        - ":fontawesome-solid-globe: TwinCAT 3 HMI": contenidos/procedimientos/hmi/tc3-hmi.md

    - ":fontawesome-solid-flask: Ejemplos":
      - ":fontawesome-solid-hand: Hola Mundo":
        - ":fontawesome-solid-file-lines: Descripción": contenidos/ejemplos/hola-mundo/index.md
        - ":fontawesome-solid-screwdriver-wrench: Implementación": contenidos/ejemplos/hola-mundo/step-by-step.md
      - ":fontawesome-solid-cart-shopping: Carro Básico":
        - ":fontawesome-solid-file-lines: Descripción": contenidos/ejemplos/carro-basico/index.md
        - ":fontawesome-solid-screwdriver-wrench: Implementación": contenidos/ejemplos/carro-basico/step-by-step.md
      - ":fontawesome-solid-cart-flatbed: Carro Extendido":
        - ":fontawesome-solid-file-lines: Descripción": contenidos/ejemplos/carro-extendido/index.md
        - ":fontawesome-solid-screwdriver-wrench: Implementación": contenidos/ejemplos/carro-extendido/step-by-step.md

    - ":fontawesome-solid-list-check: Prácticas":
      - ":fontawesome-solid-traffic-light: Semáforo": contenidos/practicas/semaforo/index.md
      - ":fontawesome-solid-cube: Proyecto Monolítico": contenidos/practicas/proyectos/proyecto-monolitico.md
      - ":fontawesome-solid-boxes-stacked: Proyecto Estructurado": contenidos/practicas/proyectos/proyecto-estructurado.md
      - Proyecto Jerárquico: contenidos/practicas/proyectos/proyecto-jerarquico.md
      - ":fontawesome-solid-puzzle-piece: Proyecto Funcional": contenidos/practicas/proyectos/proyecto-funcional.md

hooks:
  - hooks/nav_icons.py

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
      # base_path: !relative $docs_dir
      base_path: ["."]
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      # custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - search
  - include-markdown
  - macros:
      include_dir: docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/famoreno/tc3_tutorial

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/ui-course.js
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
